version: '3.8'

services:
  moodle:
    build: .
    container_name: moodle_web
    ports:
      - "8100:8100"
    volumes:
      - ./moodledata:/var/www/moodledata
      - ./config.php:/var/www/html/config.php
    depends_on:
      - mariadb
    environment:
      MOODLE_DOCKER: 1
      MOODLE_BROWSERTESTS_OUTPUT_DIR: /var/www/html/

  mariadb:
    image: mariadb:10.11
    container_name: moodle_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: example_moodle_password
    volumes:
      - ./mariadb_data:/var/lib/mysql

volumes:
  moodledata:
  mariadb_data:
